"""Index ForeignKey

Revision ID: e3ed90b1e6dc
Revises: 904217176508
Create Date: 2025-02-18 03:27:31.391354

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e3ed90b1e6dc'
down_revision: Union[str, None] = '904217176508'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('order_products_order_id_idx'), 'order_products', ['order_id'], unique=False)
    op.create_index(op.f('order_products_product_id_idx'), 'order_products', ['product_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('order_products_product_id_idx'), table_name='order_products')
    op.drop_index(op.f('order_products_order_id_idx'), table_name='order_products')
    # ### end Alembic commands ###
